# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'automacao-frontend-v1.0.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_automacao_atendimento(object):
    def setupUi(self, automacao_atendimento):
        automacao_atendimento.setObjectName("automacao_atendimento")
        automacao_atendimento.setWindowModality(QtCore.Qt.NonModal)
        automacao_atendimento.resize(280, 441)
        automacao_atendimento.setMaximumSize(QtCore.QSize(1000, 500))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        automacao_atendimento.setFont(font)
        automacao_atendimento.setIconSize(QtCore.QSize(24, 24))
        automacao_atendimento.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        automacao_atendimento.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(automacao_atendimento)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_alterarcenso = QtWidgets.QWidget()
        self.tab_alterarcenso.setObjectName("tab_alterarcenso")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_alterarcenso)
        self.verticalLayout.setObjectName("verticalLayout")
        self.atdcancelar = QtWidgets.QLabel(self.tab_alterarcenso)
        self.atdcancelar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.atdcancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.atdcancelar.setObjectName("atdcancelar")
        self.verticalLayout.addWidget(self.atdcancelar)
        self.dadoscancelamento = QtWidgets.QLineEdit(self.tab_alterarcenso)
        self.dadoscancelamento.setEnabled(True)
        self.dadoscancelamento.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dadoscancelamento.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.dadoscancelamento.setInputMask("")
        self.dadoscancelamento.setMaxLength(32767)
        self.dadoscancelamento.setAlignment(QtCore.Qt.AlignCenter)
        self.dadoscancelamento.setObjectName("dadoscancelamento")
        self.verticalLayout.addWidget(self.dadoscancelamento)
        self.atdobservacao = QtWidgets.QLabel(self.tab_alterarcenso)
        self.atdobservacao.setObjectName("atdobservacao")
        self.verticalLayout.addWidget(self.atdobservacao)
        self.dadosobservacao = QtWidgets.QLineEdit(self.tab_alterarcenso)
        self.dadosobservacao.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dadosobservacao.setAlignment(QtCore.Qt.AlignCenter)
        self.dadosobservacao.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.dadosobservacao.setObjectName("dadosobservacao")
        self.verticalLayout.addWidget(self.dadosobservacao)
        self.inserirdados = QtWidgets.QPushButton(self.tab_alterarcenso)
        self.inserirdados.setObjectName("inserirdados")
        self.verticalLayout.addWidget(self.inserirdados)
        self.exibirdados = QtWidgets.QListView(self.tab_alterarcenso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exibirdados.sizePolicy().hasHeightForWidth())
        self.exibirdados.setSizePolicy(sizePolicy)
        self.exibirdados.setMaximumSize(QtCore.QSize(1000, 500))
        self.exibirdados.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.exibirdados.setLineWidth(1)
        self.exibirdados.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.exibirdados.setTabKeyNavigation(True)
        self.exibirdados.setDragEnabled(False)
        self.exibirdados.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.exibirdados.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.exibirdados.setIconSize(QtCore.QSize(2, 2))
        self.exibirdados.setMovement(QtWidgets.QListView.Snap)
        self.exibirdados.setFlow(QtWidgets.QListView.TopToBottom)
        self.exibirdados.setResizeMode(QtWidgets.QListView.Fixed)
        self.exibirdados.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.exibirdados.setGridSize(QtCore.QSize(150, 15))
        self.exibirdados.setViewMode(QtWidgets.QListView.ListMode)
        self.exibirdados.setModelColumn(0)
        self.exibirdados.setObjectName("exibirdados")
        self.verticalLayout.addWidget(self.exibirdados)
        self.alterarcenso = QtWidgets.QPushButton(self.tab_alterarcenso)
        self.alterarcenso.setObjectName("alterarcenso")
        self.verticalLayout.addWidget(self.alterarcenso)
        self.tabWidget.addTab(self.tab_alterarcenso, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        automacao_atendimento.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(automacao_atendimento)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 280, 21))
        self.menubar.setMaximumSize(QtCore.QSize(400, 300))
        self.menubar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuCENSO = QtWidgets.QMenu(self.menubar)
        self.menuCENSO.setObjectName("menuCENSO")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        automacao_atendimento.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(automacao_atendimento)
        self.statusbar.setObjectName("statusbar")
        automacao_atendimento.setStatusBar(self.statusbar)
        self.actionSair = QtWidgets.QAction(automacao_atendimento)
        self.actionSair.setObjectName("actionSair")
        self.menuCENSO.addAction(self.actionSair)
        self.menubar.addAction(self.menuCENSO.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(automacao_atendimento)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(automacao_atendimento)

    def retranslateUi(self, automacao_atendimento):
        _translate = QtCore.QCoreApplication.translate
        automacao_atendimento.setWindowTitle(_translate("automacao_atendimento", "Automação - Atendimento"))
        self.atdcancelar.setText(_translate("automacao_atendimento", "ATD. P/ CANCELAR"))
        self.atdobservacao.setText(_translate("automacao_atendimento", "ATD P/ OBSERVAÇÕES"))
        self.inserirdados.setText(_translate("automacao_atendimento", "INSERIR"))
        self.alterarcenso.setText(_translate("automacao_atendimento", "INICIAR CANCELAMENTO"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_alterarcenso), _translate("automacao_atendimento", "Alterar Censo"))
        self.menuCENSO.setTitle(_translate("automacao_atendimento", "Arquivo"))
        self.menuHelp.setTitle(_translate("automacao_atendimento", "Help"))
        self.actionSair.setText(_translate("automacao_atendimento", "Sair"))


'''if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    automacao_atendimento = QtWidgets.QMainWindow()
    ui = Ui_automacao_atendimento()
    ui.setupUi(automacao_atendimento)
    automacao_atendimento.show()
    sys.exit(app.exec_())
'''